name: flutter_web_example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0
  backdrop: ^0.6.2
  scrollable_positioned_list: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  fonts:
    - family: HumanSans
      fonts:
        - asset: assets/fonts/HumanSans-Black.otf
          weight: 900
        # - asset: fonts/HumanSans-BlackOblique.ttf
        - asset: assets/fonts/HumanSans-Bold.otf
          weight: 700
        # - asset: fonts/HumanSans-BoldOblique.ttf
        - asset: assets/fonts/HumanSans-ExtraLight.otf
        # - asset: fonts/HumanSans-ExtraLightOblique.ttf
        - asset: assets/fonts/HumanSans-Light.otf
          weight: 300
        # - asset: fonts/HumanSans-LightOblique.ttf
        - asset: assets/fonts/HumanSans-Medium.otf
          weight: 500
        # - asset: fonts/HumanSans-MediumOblique.ttf
        - asset: assets/fonts/HumanSans-Regular.otf
          weight: 400
        # - asset: fonts/HumanSans-RegularOblique.ttf
        - asset: assets/fonts/HumanSans-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/HumanSans-Thin.otf
          weight: 100
        # - asset: fonts/HumanSans-ThinOblique.ttf



  assets:
    - assets/images/
    - assets/svg/



